name: PR Validation

on:
  pull_request:
    branches:
      - release
    types: [opened, synchronize, reopened]
    paths:
      - ".ci/config.json"
      - ".ci/*.sh"
      - ".dockerignore"
      - "linux-*.Dockerfile"
      - ".github/workflows/pr-validation.yml"
      - ".github/workflows/release.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: validate
    uses: runlix/build-workflow/.github/workflows/pr-validation-v2.yml@d8b8220e09467c81bac45f9e716e4f3c64cc0644
