name: PR Validation

on:
  pull_request:
    branches:
      - release
    types: [opened, synchronize, reopened]
    paths:
      - ".ci/config.json"
      - ".ci/*.sh"
      - ".dockerignore"
      - "linux-*.Dockerfile"
      - ".github/workflows/pr-validation.yml"
      - ".github/workflows/release.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: validate
    uses: runlix/build-workflow/.github/workflows/pr-validation.yml@86e3cbfc7b3a8093801f36bbfb2d7245bb50cb0f
    with:
      build-workflow-ref: 86e3cbfc7b3a8093801f36bbfb2d7245bb50cb0f
