name: PR Validation

on:
  pull_request:
    branches:
      - release
    types: [opened, synchronize, reopened]
    paths:
      - ".ci/config.json"
      - ".ci/README.md"
      - "linux-*.Dockerfile"
      - ".github/workflows/pr-validation.yml"
      - ".github/workflows/release.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: validate
    uses: runlix/build-workflow/.github/workflows/pr-validation-v2.yml@987962fa73ce073035aee061d6b211a7d803275b
    with:
      config-path: .ci/config.json
