name: Release

on:
  push:
    branches:
      - release
    paths:
      - ".ci/config.json"
      - ".ci/*.sh"
      - ".dockerignore"
      - "linux-*.Dockerfile"
      - ".github/workflows/release.yml"
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

jobs:
  release:
    uses: runlix/build-workflow/.github/workflows/release.yml@89677e835eb27ac46323790986bc440efe4d2f34
    with:
      tool-image: ghcr.io/runlix/build-workflow-tools:sha-7f1f00fad88250b602361378a130370a5c35420e
