name: Release

on:
  push:
    branches:
      - release
    paths:
      - ".ci/config.json"
      - ".ci/*.sh"
      - ".dockerignore"
      - "linux-*.Dockerfile"
      - ".github/workflows/release.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    uses: runlix/build-workflow/.github/workflows/release.yml@e07323d2e80025c65e2adb83771f13282e2ba0ae
