name: Sync Release Metadata

on:
  workflow_run:
    workflows:
      - Release
    branches:
      - release
    types:
      - completed

permissions:
  actions: read
  contents: write

jobs:
  sync:
    uses: runlix/build-workflow/.github/workflows/sync-release-metadata.yml@277cdc1e704b017f1f34a82de940e8c1fb0787d6
