name: Sync Release Metadata

on:
  workflow_run:
    workflows:
      - Release
    branches:
      - release
    types:
      - completed

permissions:
  actions: read
  contents: write

jobs:
  sync:
    uses: runlix/build-workflow/.github/workflows/sync-release-metadata.yml@e07323d2e80025c65e2adb83771f13282e2ba0ae
