name: Validate Release Metadata

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "release.json"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  validate-release-metadata:
    name: validate-release-metadata
    uses: runlix/build-workflow/.github/workflows/validate-release-metadata.yml@9b0699f7497afbf83bd310df5e9cfffe01e6682c
    with:
      release-json-path: release.json
