name: Validate Build

on:
  pull_request:
    branches:
      - release
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ".ci/build.json"
      - ".ci/*.sh"
      - ".dockerignore"
      - "linux-*.Dockerfile"
      - ".github/workflows/validate-build.yml"
      - ".github/workflows/publish-release.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: validate
    uses: runlix/build-workflow/.github/workflows/validate-build.yml@d6951b763c17bb92b12821acbf4ccc56e2f242ab
    with:
      tool-image: ghcr.io/runlix/build-workflow-tools:sha-d6951b763c17bb92b12821acbf4ccc56e2f242ab
