name: Validate

on:
  pull_request:
    branches:
      - release
    types: [opened, synchronize, reopened]
    paths:
      - ".ci/config.json"
      - ".ci/*.sh"
      - ".dockerignore"
      - "linux-*.Dockerfile"
      - ".github/workflows/validate.yml"
      - ".github/workflows/release.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: validate
    uses: runlix/build-workflow/.github/workflows/validate.yml@52d676ab3e20a3d661200d399fa367bf110ff968
