name: Validate

on:
  pull_request:
    branches:
      - release
    types: [opened, synchronize, reopened]
    paths:
      - ".ci/config.json"
      - ".ci/*.sh"
      - ".dockerignore"
      - "linux-*.Dockerfile"
      - ".github/workflows/validate.yml"
      - ".github/workflows/release.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: validate
    uses: runlix/build-workflow/.github/workflows/validate.yml@89677e835eb27ac46323790986bc440efe4d2f34
    with:
      tool-image: ghcr.io/runlix/build-workflow-tools:sha-7f1f00fad88250b602361378a130370a5c35420e
