name: Validate Main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "release.json"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-main:
    name: validate-main
    uses: runlix/build-workflow/.github/workflows/validate-release-json.yml@187d584d9fecd37e8026f4333c9b86ce5880a2fd
    with:
      tool-image: ghcr.io/runlix/build-workflow-tools:sha-7f1f00fad88250b602361378a130370a5c35420e
      release-json-path: release.json
