name: Validate Build

on:
  pull_request:
    branches:
      - release
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ".ci/build.json"
      - ".ci/*.sh"
      - ".dockerignore"
      - "linux-*.Dockerfile"
      - ".github/workflows/validate-build.yml"
      - ".github/workflows/publish-release.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  validate:
    name: validate
    uses: runlix/build-workflow/.github/workflows/validate-build.yml@9b0699f7497afbf83bd310df5e9cfffe01e6682c
